#+TITLE: Dap Mode
#+SETUPFILE: ../setup.org

* How To Python

  - Ensure [[https://github.com/microsoft/debugpy][debugpy]] is installed (=pip install debugpy=) in the virtual
    environment. I install this by default in new virtual environments (see:
    [[https://github.com/cfclrk/dotfiles/blob/master/.pyenv/default_packages][.pyenv/default_packages]]).

  In source file, move point somewhere you want a breakpoint, and run
  =M-x dap-breakpoint-toggle=

  Go to test file, move point to a test. Run =dap-debug=. Select option to run
  the pytest test at point.

** Jumping in the Stack

   You can jump forward or backward in the stack. Use =M-x
   dap-switch-stack-frame=, or click around in the "Debug Sessions" dap buffer.

   TODO: How does this work? Does this only work in languages with first-class
   continuations? How much program state is actually restored?

  - =dap-disconnect= Quit the debugging session

** Rerun Last

   =dap=

* Old Sessions

  Saves output from old debug sessions

  Delete them in the =dap-ui-sessions= buffer, =D=
