#+TITLE: Getting Help
#+SETUPFILE: ../../setup.org

* Workflow

  If it's about Emacs Lisp:

  - Invoke the info manual: =C-h i=
  - Find the Elisp manual: =m Elisp=
  - Search the index for, say, "defvar": =i defvar=

  If it's about a specific package, and you know what the package is called:

  - =C-h P=, which runs =describe-package=

  You can also evaluate a lisp form to jump to info docs. For example:

  #+begin_src emacs-lisp
    (info "(elisp) Packaging")
  #+end_src

* apropos

  =M-x apropos=, then type the part of the function name you remember.

* Info-mode Invocation

  =C-h i= to get the top-level info

  =M-x info-display-manual= to get a specific manual (TODO: bind to =C-h RET=)

* Info-mode Navigation

  =^= to go up

  =n/p= next/previous node (not child node!)

  I find this confusing because many modes (dired, magit) bind =n= and =p= to
  move up and down. Although n/p does work from top-level node of a mode's help.
  Hm.

  =m= Pick menu item by name. Super useful.

  =d= Go to top-level node.

* Alternatives?

  Info is an emacs-only format. There are other possible formats, and there have
  been proposals to change the Emacs help system to use a different format.
